api:
  security:
    token:
      secret: secret123secret123secret123secret123secret123secret123secret123secret123secret123secret123secret123
      issuer: coffee-api
      expiration-date-in-seconds: 3600

date:
  zone:
    off-set: "-03:00"

cors:
  origin-patterns: http://localhost:8080,http://localhost:4200
  allowed-methods: POST,GET,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type
  max-age-cache-seconds: 3600
spring:
  application:
    name: Coffee-Api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/coffee-db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: rootpassword

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    open-in-view: false


logging:
  level:
    root: INFO


spring-doc:
  paths-to-match: /api/v1/**
  swagger-ui:
    use-root-path: true
