CREATE TABLE IF NOT EXISTS `coffee-db`.`roles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `role_UNIQUE` (`name` ASC) VISIBLE
) ENGINE = InnoDB
COMMENT = 'CASHIER, MANAGER, ATTENDANT'