CREATE TABLE IF NOT EXISTS `coffee-db`.`roles` (
  `id` BIGINT NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `role_UNIQUE` (`role` ASC) VISIBLE
) ENGINE = InnoDB COMMENT = 'CASHIER, MANAGER, ATTENDANT'