INSERT INTO `coffee-db`.`units` (id, name, acronym) VALUES
    (1, "Mililitro", "mL"),
    (2, "Litro", "L"),
    (3, "Onça fluida", "fl oz"),
    (4, "Grama", "g"),
    (5, "Quilograma", "kg"),
    (6, "Libra", "lb"),
    (7, "Xícara", "cup"),
    (8, "Unidade", "un"),
    (9, "Colher de sopa", "tbsp"),
    (10, "Colher de chá", "tsp"),
    (11, "Pedaço", "pc"),
    (12, "Porção", "serv"),
    (13, "Fatias", "slc"),
    (14, "Lata", "can"),
    (15, "Garrafa", "btl"),
    (16, "Pacote", "pkg"),
    (17, "Barrinha", "bar"),
    (18, "Sachê", "sachet");
