services:
  mysql-dev:
    image: mysql:8.1
    container_name: coffee-db-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: coffee-db
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - "3308:3306"
